name: push_action
on: [push]
jobs:
    train-and-run-model:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: set up python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8.5'
        - name: Install dependencies
          run: python -m pip install -r requirements.txt
        - name: Train model
          run: python src/models/Ecoli_Trainieren.py
        - name: Predict model
          run: python src/models/Ecoli_Bestimmen.py
        - name: Archive production artifacts
          uses: actions/upload-artifact@v2
          with:
            name: classifier_object.pickle
            path: models/classifier_object.pickle
        - name: Archive production artifacts
          uses: actions/upload-artifact@v2
          with:
            name: scaler_object.pickle
            path: models/scaler_object.pickle